### ISSUE TITLE
trying to login but this error i get

### ISSUE THREAD

**Issue by AhmedGamal111** [uname-yang/mycloudhome#2]
I am using the command "mycloudhome --debug login --username xxx --password xxx"
after changing "xxx" to my username and password I get the following error

Traceback (most recent call last):
  File "/home/ahmed/.local/bin/mycloudhome", line 11, in <module>
    sys.exit(cli())
  File "/home/ahmed/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ahmed/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ahmed/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ahmed/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ahmed/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ahmed/.local/lib/python3.6/site-packages/mycloudhome/main.py", line 26, in login
    click.echo(utils.pretty(auth.login(username, password)))
  File "/home/ahmed/.local/lib/python3.6/site-packages/mycloudhome/auth.py", line 10, in login
    token = fetch_token(username, password)
  File "/home/ahmed/.local/lib/python3.6/site-packages/mycloudhome/auth.py", line 34, in fetch_token
    response.status_code, response.content))
Exception: Login Error !!! [500][b'"Content type \'application/x-www-form-urlencoded;charset=UTF-8\' not supported"']

**Comment by uname-yang** [comment]
It seems the WD changed their api, I will fix it soon.

**Comment by AhmedGamal111** [comment]
I am very pleased with your response and i waiting yor fix
Thank you

**Comment by uname-yang** [comment]
please try the new version 2020.12.12.1
